# Template that can be used to load the moveit_simple_controller_manager
# implementation as a MoveIt! controller for the Ur arm.
controller_list:
  - name: ur 
    action_ns: joint_trajectory_action
    type: FollowJointTrajectory
    default: true
    joints:
      - ur_arm_0_joint
      - ur_arm_1_joint
      - ur_arm_2_joint
      - ur_arm_3_joint
      - ur_arm_4_joint
      - ur_arm_5_joint
      - ur_finger_joint_0
      - ur_finger_joint_2
      - ur_finger_joint_4
