<?xml version="1.0" encoding="UTF-8"?>
<!--
 Provides a xacro macro to insert the ur robot arm.
 NOTE: The gazebo plugins to control the arm are *not* loaded
 from within this file, in order to avoid dependencies to other
 packages. You will have to add the <gazebo> tags to load the
 model plugins from where you call this xacro macro.
 This file however *can* include the <transmission> tags
 for the joints (include file "$(find ur_description)/urdf/ur_joint_control.xacro")
 and/or "$(find ur_description)/urdf/ur_joint_control_vel.xacro")
 according to arguments add_transmission_pos and add_transmission_vel.
-->
<root
 xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
 xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
 xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
 xmlns:xacro="http://ros.org/wiki/xacro">

    <!-- add transmission tags for position controllers -->
    <xacro:arg name="add_transmission_pos" default="false"/>
    <!-- add transmission tags for velocity controllers -->
    <xacro:arg name="add_transmission_vel" default="false"/>

  <xacro:macro name="default_material">
    <mu1>100000</mu1>
    <mu2>100000</mu2>
     <kp>100000000.0</kp>
     <kd>1.0</kd>
  </xacro:macro>

  <xacro:macro name="arm_0_limits">
    <limit effort="80" velocity="1.0" />
  </xacro:macro>


  <xacro:macro name="arm_1_limits" params="l u">
    <limit lower="${l}" upper="${u}" effort="80" velocity="1.0" />
  </xacro:macro>

    <xacro:macro name="arm_2_limits" params="l u">
    <limit lower="${l}" upper="${u}" effort="4" velocity="1.0" />
  </xacro:macro>

  <xacro:macro name="arm_3_limits">
    <limit effort="10.5" velocity="1.0" />
  </xacro:macro>

  <xacro:macro name="arm_4_limits">
    <limit effort="10.0" velocity="1.0" />
  </xacro:macro>

    <xacro:macro name="arm_5_limits">
    <limit effort="10.0" velocity="1.0" />
  </xacro:macro>

  <!--- remark 2014: damping greater than 0.5 lead to model break downs when testing it bit by bit -->
    <xacro:macro name="default_damping_low">
    <dynamics damping="0.05" friction="0.05"/>
  </xacro:macro>

  <xacro:macro name="default_damping_medium">
    <dynamics damping="0.5" friction="0.5"/>
  </xacro:macro>

  <xacro:macro name="default_damping_high">
    <dynamics damping="0.7" friction="1.0"/>
  </xacro:macro>

  <!-- Formula according to https://en.wikipedia.org/wiki/List_of_moment_of_inertia_tensors for cylinder -->
  <xacro:macro name="cyl_inertia" params="mass r h ">
    <mass value="${mass}"/>
    <inertia ixx="${0.083333 * mass * (3*r*r + h*h)}" ixy="0" ixz="0"
                 iyy="${0.083333 * mass * (3*r*r + h*h)}" iyz="0"
                 izz="${0.5*mass*r*r}" />
  </xacro:macro>

    <!-- fake cylinder which is actually a box -->
  <!--xacro:macro name="cyl_inertia" params="mass r h ">
      <mass value="${mass}"/>
      <inertia
      ixx="${mass / 12.0 * (r*r + h*h)}" ixy="0.0" ixz="0.0"
      iyy="${mass / 12.0 * (h*h + r*r)}" iyz="0.0"
      izz="${mass / 12.0 * (r*r + r*r)}"/>
  </xacro:macro-->


  <xacro:macro name="testSphere">
<!--     <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <sphere radius="0.005"/>
      </geometry>
      <material name="">
        <color rgba="0.10 0.10 0.10 1" />
      </material>
    </visual>
-->
  </xacro:macro>

  <xacro:property name="M_PI" value="3.14159265358979" />
  <xacro:property name="M_PI_2" value="1.5707963267949" />
  <xacro:property name="M_PI_4" value="0.785398163" />


  <!-- ***************** MODEL CORRECTIONS ************************* -->

  <!-- MODEL_FIX corrections for hand limb, which is not modelled correctly.
  <xacro:property name="wrist_scale_x" value="1.0"/>
  <xacro:property name="wrist_scale_y" value="1.0"/>
  <xacro:property name="wrist_scale_z" value="1.0"/>
  -->
  <xacro:property name="wrist_scale_x" value="1.0"/>
  <xacro:property name="wrist_scale_y" value="1.0"/>
  <xacro:property name="wrist_scale_z" value="1.0"/>

  <!-- MODEL_FIX transform of base to first joint as derived from DH specs is not exact, this is a correction
  <xacro:property name="base_height_corr" value="0"/>
  <xacro:property name="base_height_corr" value="0"/>
-->
  <xacro:property name="base_height_corr" value="0"/>
  <xacro:property name="base_height_corr" value="0"/>





  <!-- MACRO FOR THE ROBOT ARM -->
  <xacro:macro name="ur_arm" params="parent mass_divider finger_mass_divider *origin ur_prefix:=ur">

    <joint name="${ur_prefix}_arm_joint" type="fixed">
    <xacro:insert_block name="origin" />
    <parent link="${parent}" />
        <child link="${ur_prefix}_0_baseA" />
  </joint>

  <!-- for some reason, material only applies if full name specified...
       these only seem to work in older gazebo versions -->
  <gazebo reference="${ur_prefix}_ring_">
    <material>Gazebo/Grey</material>
    <implicitSpringDamper>1</implicitSpringDamper>
    <xacro:default_material/>
  </gazebo>
  <gazebo reference="_limb">
    <material>Gazebo/FlatBlack</material>
    <implicitSpringDamper>1</implicitSpringDamper>
    <xacro:default_material/>
  </gazebo>

  <!-- for some reason, material only applies if full name specified -->
  <gazebo reference="${ur_prefix}base">
    <material>Gazebo/White</material>
    <xacro:default_material/>
  </gazebo>
  <gazebo reference="${ur_prefix}_finger_joint_0">
    <provideFeedback value="true"/>
  </gazebo>
    <gazebo reference="${ur_prefix}_finger_joint_2">
    <provideFeedback value="true"/>
  </gazebo>
    <gazebo reference="${ur_prefix}_finger_joint_4">
    <provideFeedback value="true"/>
  </gazebo>
    <xacro:if value="$(arg add_transmission_pos)">
        <xacro:include filename="$(find ur_description)/urdf/ur_joint_control.xacro"/>
        <xacro:ur_joint_control ur_prefix="${ur_prefix}"/>
    </xacro:if>

    <xacro:if value="$(arg add_transmission_vel)">
        <xacro:include filename="$(find ur_description)/urdf/ur_joint_control_vel.xacro"/>
        <xacro:ur_joint_control_vel ur_prefix="${ur_prefix}"/>
    </xacro:if>

  <xacro:property name="pi" value="3.14159265" />

  <!-- Inertia parameters -->
  <xacro:property name="base_mass" value="4.0" />  <!-- This mass might be incorrect -->
  <xacro:property name="shoulder_mass" value="3.7000" />
  <xacro:property name="upper_arm_mass" value="8.3930" />
  <xacro:property name="forearm_mass" value="2.2750" />
  <xacro:property name="wrist_1_mass" value="1.2190" />
  <xacro:property name="wrist_2_mass" value="1.2190" />
  <xacro:property name="wrist_3_mass" value="0.1879" />

  <xacro:property name="shoulder_cog" value="0.0 0.00193 -0.02561" />
  <xacro:property name="upper_arm_cog" value="0.0 -0.024201 0.2125" />
  <xacro:property name="forearm_cog" value="0.0 0.0265 0.11993" />
  <xacro:property name="wrist_1_cog" value="0.0 0.110949 0.01634" />
  <xacro:property name="wrist_2_cog" value="0.0 0.0018 0.11099" />
  <xacro:property name="wrist_3_cog" value="0.0 0.001159 0.0" />

  <!-- Kinematic model -->
  <!-- Properties from urcontrol.conf -->
  <!--
    DH for UR5:
    a = [0.00000, -0.42500, -0.39225,  0.00000,  0.00000,  0.0000]
    d = [0.089159,  0.00000,  0.00000,  0.10915,  0.09465,  0.0823]
    alpha = [ 1.570796327, 0, 0, 1.570796327, -1.570796327, 0 ]
    q_home_offset = [0, -1.570796327, 0, -1.570796327, 0, 0]
    joint_direction = [-1, -1, 1, 1, 1, 1]
    mass = [3.7000, 8.3930, 2.2750, 1.2190, 1.2190, 0.1879]
    center_of_mass = [ [0, -0.02561, 0.00193], [0.2125, 0, 0.11336], [0.11993, 0.0, 0.0265], [0, -0.0018, 0.01634], [0, 0.0018,0.01634], [0, 0, -0.001159] ]
  -->
  <xacro:property name="ur_d1" value="0.089159" />
  <xacro:property name="ur_a2" value="-0.42500" />
  <xacro:property name="ur_a3" value="-0.39225" />
  <xacro:property name="ur_d4" value="0.10915" />
  <xacro:property name="ur_d5" value="0.09465" />
  <xacro:property name="ur_d6" value="0.0823" />

  <!-- Arbitrary offsets for shoulder/elbow joints -->
  <xacro:property name="shoulder_offset" value="0.13585" />  <!-- measured from model -->
  <xacro:property name="elbow_offset" value="-0.1197" /> <!-- measured from model -->

  <!-- link lengths used in model -->
  <xacro:property name="shoulder_height" value="${ur_d1}" />
  <xacro:property name="upper_arm_length" value="${-ur_a2}" />
  <xacro:property name="forearm_length" value="${-ur_a3}" />
  <xacro:property name="wrist_1_length" value="${ur_d4 - elbow_offset - shoulder_offset}" />
  <xacro:property name="wrist_2_length" value="${ur_d5}" />
  <xacro:property name="wrist_3_length" value="${ur_d6}" />
  <!--property name="shoulder_height" value="0.089159" /-->
  <!--property name="shoulder_offset" value="0.13585" /-->  <!-- shoulder_offset - elbow_offset + wrist_1_length = 0.10915 -->
  <!--property name="upper_arm_length" value="0.42500" /-->
  <!--property name="elbow_offset" value="0.1197" /-->       <!-- CAD measured -->
  <!--property name="forearm_length" value="0.39225" /-->
  <!--property name="wrist_1_length" value="0.093" /-->     <!-- CAD measured -->
  <!--property name="wrist_2_length" value="0.09465" /-->   <!-- In CAD this distance is 0.930, but in the spec it is 0.09465 -->
  <!--property name="wrist_3_length" value="0.0823" /-->

  <xacro:property name="shoulder_radius" value="0.060" />   <!-- manually measured -->
  <xacro:property name="upper_arm_radius" value="0.054" />  <!-- manually measured -->
  <xacro:property name="elbow_radius" value="0.060" />      <!-- manually measured -->
  <xacro:property name="forearm_radius" value="0.040" />    <!-- manually measured -->
  <xacro:property name="wrist_radius" value="0.045" />      <!-- manually measured -->

  <xacro:macro name="cylinder_inertial" params="radius length mass *origin">
    <inertial>
      <mass value="${mass}" />
      <xacro:insert_block name="origin" />
      <inertia ixx="${0.0833333 * mass * (3 * radius * radius + length * length)}" ixy="0.0" ixz="0.0"
        iyy="${0.0833333 * mass * (3 * radius * radius + length * length)}" iyz="0.0"
        izz="${0.5 * mass * radius * radius}" />
    </inertial>
  </xacro:macro>
  
  <link name="${ur_prefix}_0_baseA">
    <inertial>
      <origin xyz="0 0 0.0" rpy="0 0 0" />
      <xacro:cyl_inertia mass="${0.5688}" h="0.059" r="0.036"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://ur_description/meshes/ur/base.stl"/>
      </geometry>
      <material name="">
        <color rgba="0.65 0.65 0.66 1" />
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://ur_description/meshes/ur/base.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </collision>
  </link>
   <link name="${ur_prefix}_0_baseB_limb">
    <inertial>
      <origin xyz="0 0 0.0" rpy="0 0 0" />
      <xacro:cyl_inertia mass="${0.5688}" h="0.059" r="0.036"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://ur_description/meshes/ur/base.stl"/>
      </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://ur_description/meshes/ur/base.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </collision>

  </link>
    <joint name="${ur_prefix}_base_internal" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
        <parent link="${ur_prefix}_0_baseA" />
        <child link="${ur_prefix}_0_baseB_limb" />
    <axis xyz="0 0 0" />
  </joint>

    <joint name="${ur_prefix}_arm_0_joint" type="revolute">
      <parent link="${ur_prefix}_0_baseB_limb" />
      <child link = "${ur_prefix}_1_shoulder_limb" />
      <origin xyz="0.0 0.0 ${shoulder_height}" rpy="0.0 0.0 0.0" />
      <axis xyz="0 0 1" />
      <limit lower="${-20.0 * pi}" upper="${20.0 * pi}" effort="1500.0" velocity="3.15"/>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <link name="${ur_prefix}_1_shoulder_limb">
      <visual>
        <geometry>
          <mesh filename="package://ur_description/meshes/ur/shoulder.dae" />
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://ur_description/meshes/ur/shoulder.stl" scale="0.001 0.001 0.001"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="0.06" length="0.15" mass="${shoulder_mass}">
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>

    <joint name="${ur_prefix}_arm_1_joint" type="revolute">
      <parent link="${ur_prefix}_1_shoulder_limb" />
      <child link = "${ur_prefix}_2_upperarm_limb" />
      <origin xyz="0.0 ${shoulder_offset} 0.0" rpy="0.0 ${pi / 2.0} 0.0" />
      <axis xyz="0 1 0" />
      <limit lower="${-20.0 * pi}" upper="${20.0 * pi}" effort="1500.0" velocity="3.15"/>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <link name="${ur_prefix}_2_upperarm_limb">
      <visual>
        <geometry>
          <mesh filename="package://ur_description/meshes/ur/upperarm.dae" />
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://ur_description/meshes/ur/upperarm.stl" scale="0.001 0.001 0.001"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="0.06" length="0.56" mass="${upper_arm_mass}">
        <origin xyz="0.0 0.0 0.28" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>

    <joint name="${ur_prefix}_arm_2_joint" type="revolute">
      <parent link="${ur_prefix}_2_upperarm_limb" />
      <child link = "${ur_prefix}_3_forearm_limb" />
      <origin xyz="0.0 ${elbow_offset} ${upper_arm_length}" rpy="0.0 0.0 0.0" />
      <axis xyz="0 1 0" />
      <limit lower="${-20.0 * pi}" upper="${20.0 * pi}" effort="150.0" velocity="3.15"/>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <link name="${ur_prefix}_3_forearm_limb">
      <visual>
        <geometry>
          <mesh filename="package://ur_description/meshes/ur/forearm.dae" />
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://ur_description/meshes/ur/forearm.stl" scale="0.001 0.001 0.001"/>
        </geometry>
              <surface>
        <contact>
          <collide_without_contact>true</collide_without_contact>
        </contact>
      </surface>
      </collision>
      <xacro:cylinder_inertial radius="0.06" length="0.5" mass="${forearm_mass}">
        <origin xyz="0.0 0.0 0.25" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>

    <joint name="${ur_prefix}_arm_3_joint" type="revolute">
      <parent link="${ur_prefix}_3_forearm_limb" />
      <child link = "${ur_prefix}_4_upperwrist_limb" />
      <origin xyz="0.0 0.0 ${forearm_length}" rpy="0.0 ${pi / 2.0} 0.0" />
      <axis xyz="0 1 0" />
      <limit lower="${-20.0 * pi}" upper="${20.0 * pi}" effort="280.0" velocity="3.2"/>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <link name="${ur_prefix}_4_upperwrist_limb">
      <visual>
        <geometry>
          <mesh filename="package://ur_description/meshes/ur/wrist1.dae" />
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://ur_description/meshes/ur/wrist1.stl" scale="0.001 0.001 0.001"/>
        </geometry>
              <surface>
        <contact>
          <collide_without_contact>true</collide_without_contact>
        </contact>
      </surface>
      </collision>
      <xacro:cylinder_inertial radius="0.6" length="0.12" mass="${wrist_1_mass}">
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>

    <joint name="${ur_prefix}_arm_4_joint" type="revolute">
      <parent link="${ur_prefix}_4_upperwrist_limb" />
      <child link = "${ur_prefix}_5_lowerwrist_limb" />
      <origin xyz="0.0 ${wrist_1_length} 0.0" rpy="0.0 0.0 0.0" />
      <axis xyz="0 0 1" />
      <limit lower="${-20.0 * pi}" upper="${20.0 * pi}" effort="280.0" velocity="3.2"/>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <link name="${ur_prefix}_5_lowerwrist_limb">
      <visual>
        <geometry>
          <mesh filename="package://ur_description/meshes/ur/wrist2.dae" />
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://ur_description/meshes/ur/wrist2.stl" scale="0.001 0.001 0.001"/>
        </geometry>
              <surface>
        <contact>
          <collide_without_contact>true</collide_without_contact>
        </contact>
      </surface>
      </collision>
      <xacro:cylinder_inertial radius="0.6" length="0.12" mass="${wrist_2_mass}">
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>

    <joint name="${ur_prefix}_arm_5_joint" type="revolute">
      <parent link="${ur_prefix}_5_lowerwrist_limb" />
      <child link = "${ur_prefix}_6_hand_limb" />
      <origin xyz="0.0 0.0 ${wrist_2_length}" rpy="0.0 0.0 0.0" />
      <axis xyz="0 1 0" />
      <limit lower="${-20.0 * pi}" upper="${20.0 * pi}" effort="280.0" velocity="3.2"/>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <link name="${ur_prefix}_6_hand_limb">
      <visual>
        <geometry>
          <mesh filename="package://ur_description/meshes/ur/wrist3.dae" />
        </geometry>
        <material name="LightGrey">
          <color rgba="0.2 0.2 0.2 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://ur_description/meshes/ur/wrist3.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <surface>
        <contact>
          <collide_without_contact>true</collide_without_contact>
        </contact>
        </surface>
      </collision>
      <xacro:cylinder_inertial radius="0.6" length="0.12" mass="${wrist_3_mass}">
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>





    <joint name="${ur_prefix}_finger_joint_0" type="revolute">
      <parent link="${ur_prefix}_ee_link" />
      <child link = "${ur_prefix}_ee_0_link" />
      <origin xyz="0.0 0.0 ${wrist_2_length}" rpy="0.0 0.0 0.0" />
      <axis xyz="0 1 0" />
      <limit lower="${-20.0 * pi}" upper="${20.0 * pi}" effort="0.01" velocity="3.2"/>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <joint name="${ur_prefix}_finger_joint_2" type="revolute">
      <parent link="${ur_prefix}_ee_link" />
      <child link = "${ur_prefix}_ee_1_link" />
      <origin xyz="0.0 0.0 ${wrist_2_length}" rpy="0.0 0.0 0.0" />
      <axis xyz="0 1 0" />
      <limit lower="${-20.0 * pi}" upper="${20.0 * pi}" effort="0.01" velocity="3.2"/>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <joint name="${ur_prefix}_finger_joint_4" type="revolute">
      <parent link="${ur_prefix}_ee_link" />
      <child link = "${ur_prefix}_ee_2_link" />
      <origin xyz="0.0 0.0 ${wrist_2_length}" rpy="0.0 0.0 0.0" />
      <axis xyz="0 1 0" />
      <limit lower="${-20.0 * pi}" upper="${20.0 * pi}" effort="0.01" velocity="3.2"/>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>




    <joint name="${ur_prefix}_ee_0_fixed_joint" type="fixed">
      <parent link="${ur_prefix}_6_hand_limb" />
      <child link = "${ur_prefix}_ee_0_link" />
      <origin xyz="0.0 ${wrist_3_length} 0.0" rpy="0.0 0.0 ${pi/2.0}" />
    </joint>

    <link name="${ur_prefix}_ee_0_link">
      <xacro:cylinder_inertial radius="0.06" length="0.012" mass="${wrist_1_mass}">
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>



    <joint name="${ur_prefix}_ee_1_fixed_joint" type="fixed">
      <parent link="${ur_prefix}_6_hand_limb" />
      <child link = "${ur_prefix}_ee_1_link" />
      <origin xyz="0.0 ${wrist_3_length} 0.0" rpy="0.0 0.0 ${pi/2.0}" />
    </joint>

    <link name="${ur_prefix}_ee_1_link">
      <xacro:cylinder_inertial radius="0.06" length="0.012" mass="${wrist_1_mass}">
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>



    <joint name="${ur_prefix}_ee_2_fixed_joint" type="fixed">
      <parent link="${ur_prefix}_6_hand_limb" />
      <child link = "${ur_prefix}_ee_2_link" />
      <origin xyz="0.0 ${wrist_3_length} 0.0" rpy="0.0 0.0 ${pi/2.0}" />
    </joint>

    <link name="${ur_prefix}_ee_2_link">
      <xacro:cylinder_inertial radius="0.06" length="0.012" mass="${wrist_1_mass}">
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>



    <joint name="${ur_prefix}_ee_fixed_joint" type="fixed">
      <parent link="${ur_prefix}_6_hand_limb" />
      <child link = "${ur_prefix}_ee_link" />
      <origin xyz="0.0 ${wrist_3_length} 0.0" rpy="0.0 0.0 ${pi/2.0}" />
    </joint>

    <link name="${ur_prefix}_ee_link">
      <collision>
        <geometry>
          <box size="0.01 0.01 0.01"/>
        </geometry>
        <origin rpy="0 0 0" xyz="-0.01 0 0"/>
      </collision>
      <xacro:cylinder_inertial radius="0.06" length="0.012" mass="${wrist_1_mass}">
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>






    <!-- ROS _0_baseB_limb to UR 'Base' Coordinates transform -->
    <link name="${ur_prefix}base"/>
    <joint name="${ur_prefix}_0_baseB_limb-base_fixed_joint" type="fixed">
      <!-- NOTE: this rotation is only needed as long as _0_baseB_limb itself is
                 not corrected wrt the real robot (ie: rotated over 180
                 degrees)
      -->
      <origin xyz="0 0 0" rpy="0 0 ${-pi}"/>
      <parent link="${ur_prefix}_0_baseB_limb"/>
      <child link="${ur_prefix}base"/>
    </joint>

    <!-- Frame coincident with all-zeros TCP on UR controller -->
    <link name="${ur_prefix}tool0"/>
    <joint name="${ur_prefix}_6_hand_limb-tool0_fixed_joint" type="fixed">
      <origin xyz="0 ${wrist_3_length} 0" rpy="${pi/-2.0} 0 0"/>
      <parent link="${ur_prefix}_6_hand_limb"/>
      <child link="${ur_prefix}tool0"/>
    </joint>

  </xacro:macro>






</root>
