ur:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100  

  # Position Controllers ---------------------------------------
  ur_arm_0_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: ur_arm_0_joint
    pid: {p: 100.0, i: 0.5, d: 1.0}
  ur_arm_1_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: ur_arm_1_joint
    pid: {p: 100.0, i: 0.5, d: 5.0}
  ur_arm_2_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: ur_arm_2_joint
    pid: {p: 100.0, i: 0.5, d: 1.0}
  ur_arm_3_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: ur_arm_3_joint
    pid: {p: 100.0, i: 0.5, d: 1.0}
  ur_arm_4_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: ur_arm_4_joint
    pid: {p: 10.0, i: 0.5, d: 1.0}
  ur_arm_5_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: ur_arm_5_joint
    pid: {p: 10.0, i: 0.5, d: 1.0}
  ur_finger_joint_0_position_controller:
    type: effort_controllers/JointPositionController
    joint: ur_finger_joint_0
    pid: {p: 10, i: 0.0001, d: 0.005}
  ur_finger_joint_2_position_controller:
    type: effort_controllers/JointPositionController
    joint: ur_finger_joint_2
    pid: {p: 10, i: 0.0001, d: 0.005}
  ur_finger_joint_4_position_controller:
    type: effort_controllers/JointPositionController
    joint: ur_finger_joint_4
    pid: {p: 10, i: 0.0001, d: 0.005}

  # Velocity Controllers ---------------------------------------
  ur_arm_0_joint_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: ur_arm_0_joint
    pid: {p: 100.0, i: 0.5, d: 1.0}
  ur_arm_1_joint_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: ur_arm_1_joint
    pid: {p: 100.0, i: 0.5, d: 1.0}
  ur_arm_2_joint_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: ur_arm_2_joint
    pid: {p: 100.0, i: 0.5, d: 1.0}
  ur_arm_3_joint_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: ur_arm_3_joint
    pid: {p: 100.0, i: 0.5, d: 1.0}
  ur_arm_4_joint_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: ur_arm_4_joint
    pid: {p: 10.0, i: 0.5, d: 1.0}
  ur_arm_5_joint_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: ur_arm_5_joint
    pid: {p: 10.0, i: 0.5, d: 1.0}
  ur_finger_joint_0_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: ur_finger_joint_0
    pid: {p: 10, i: 0.0001, d: 0.005}
  ur_finger_joint_2_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: ur_finger_joint_2
    pid: {p: 10, i: 0.0001, d: 0.005}
  ur_finger_joint_4_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: ur_finger_joint_4
    pid: {p: 10, i: 0.0001, d: 0.005}