# PID values to use for UrJointControlLocalImpl if Joint::SetVelocity()
# is to be used instead of Joint::SetForce().

ur:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100  

  # Position Controllers ---------------------------------------
  ur_arm_0_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: ur_arm_0_joint
    pid: {p: 20, i: 1.0, d: 0}
  ur_arm_1_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: ur_arm_1_joint
    pid: {p: 20, i: 1.0, d: 0}
  ur_arm_2_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: ur_arm_2_joint
    pid: {p: 20, i: 1.0, d: 0}
  ur_arm_3_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: ur_arm_3_joint
    pid: {p: 20, i: 1.0, d: 0}
  ur_arm_4_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: ur_arm_4_joint
    pid: {p: 20, i: 1.0, d: 0}
  ur_arm_5_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: ur_arm_5_joint
    pid: {p: 20, i: 1.0, d: 0}

  # Velocity Controllers ---------------------------------------
  # old values for all: p: 0.8 i: 0.4 d: 0
  ur_arm_0_joint_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: ur_arm_0_joint
    pid: {p: 0.4, i: 0, d: 0}  
  ur_arm_1_joint_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: ur_arm_1_joint
    pid: {p: 0.4, i: 0, d: 0}
  ur_arm_2_joint_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: ur_arm_2_joint
    pid: {p: 0.4, i: 0, d: 0}
  ur_arm_3_joint_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: ur_arm_3_joint
    pid: {p: 0.4, i: 0, d: 0}
  ur_arm_4_joint_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: ur_arm_4_joint
    pid: {p: 0.4, i: 0, d: 0}
  ur_arm_5_joint_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: ur_arm_5_joint
    pid: {p: 0.4, i: 0, d: 0}
